pipeline:
  name: Build pawtraits
  identifier: Build_pawtraits_1781217201048
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: viral
                    repo: viralpatel1994/pawtraits
                    tags:
                      - latest
              - stepGroup:
                  name: sec
                  identifier: sec
                  steps:
                    - parallel:
                        - step:
                            type: Owasp
                            name: Owasp_1
                            identifier: Owasp_1
                            spec:
                              target:
                                detection: auto
                                type: repository
                              advanced:
                                log:
                                  level: info
                                args: {}
                              mode: orchestration
                              config: default
                        - step:
                            type: OsvScanner
                            name: OsvScanner_1
                            identifier: OsvScanner_1
                            spec:
                              target:
                                detection: auto
                                type: repository
                              advanced:
                                log:
                                  level: info
                                args: {}
                              mode: orchestration
                              config: default
                        - step:
                            type: Gitleaks
                            name: Gitleaks_1
                            identifier: Gitleaks_1
                            spec:
                              target:
                                detection: auto
                                type: repository
                              advanced:
                                log:
                                  level: info
                                args: {}
                              mode: orchestration
                              config: default
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        description: ""
  properties:
    ci:
      codebase:
        connectorRef: harnessgitconnector
        repoName: pawtraits
        build: <+input>
