pipeline:
  name: pawtraits
  identifier: Build_pawtraits_1781217201048
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        template:
          templateRef: build_scan_push
          versionLabel: "1"
    - stage:
        name: mini kube deploy
        identifier: mini_kube_deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: paw
          environment:
            environmentRef: viralstg
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infra
          execution:
            steps:
              - step:
                  name: rollling
                  identifier: rollling
                  template:
                    templateRef: paw_rolling
                    versionLabel: "1"
              - step:
                  type: Email
                  name: viral email
                  identifier: viral_email
                  spec:
                    to: viralpatel94@gmail.com
                    cc: ""
                    subject: build success
                    body: great success
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  properties:
    ci:
      codebase:
        connectorRef: harnessgitconnector
        repoName: pawtraits
        build: <+input>
  tags: {}
  notificationRules:
    - name: viral
      identifier: viral
      pipelineEvents:
        - type: PipelineFailed
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - viralpatel94@gmail.com
      enabled: true
